### ISSUE TITLE
Linux python errors

### ISSUE THREAD

**Issue by pe1rrr** [PaulOfford/mbserver#6]
Hi Paul

Any idea what this may be referring to?

```
pi@superbox:~/microblog $ python3 mb_server.py 
2023-02-13 04:23:47Z - info: Microblog Server revision 8
2023-02-13 04:23:47Z - info: Connecting to JS8Call at 127.0.0.1:2442
2023-02-13 04:23:47Z - info: Connected to JS8Call
Traceback (most recent call last):
  File "/mnt/disk1/home/pi/microblog/mb_server.py", line 640, in <module>
    main()
  File "/mnt/disk1/home/pi/microblog/mb_server.py", line 635, in main
    s.run_server()
  File "/mnt/disk1/home/pi/microblog/mb_server.py", line 602, in run_server
    mb_announcement.send_mb_announcement(js8call_api)
  File "/mnt/disk1/home/pi/microblog/mb_server.py", line 515, in send_mb_announcement
    self.latest_post_meta()  # update with the latest post info
  File "/mnt/disk1/home/pi/microblog/mb_server.py", line 504, in latest_post_meta
    latest_listing = file_list[len(file_list) - 1]
IndexError: list index out of range
```

🤔

**Comment by alexpaths** [comment]
I suspect the program can't find your posts directory.

The `posts_dir` variable in `server_settings.py` needs to be changed to your posts directory. To use the directory included in the repository, set `posts_dir = 'posts/'`

73 KJ6FEC

**Comment by PaulOfford** [comment]
Thanks for pitching in here, Alex ( @alexpaths ).  I've added code to the latest revision of the server to check that the posts directory exists.  If the posts_dir setting is incorrect, we now throw a console message and the server doesn't start.

@pe1rrr  - did Alex's suggestion fix the problem?>

**Comment by PaulOfford** [comment]
Closed fixed.
